### Users show request

GET http://localhost:3000/users/1.json

### Users create action

POST http://localhost:3000/users.json
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "Test",
  "phone_number": "5557775555",
  "email": "ts@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users update action

PATCH http://localhost:3000/users/2.json
Content-Type: application/json

{
  "first_name": "Michelle",
  "last_name": "Visage",
  "email": "michelle@test.com"
}
###

PATCH http://localhost:3000/users/3.json
Content-Type: application/json

{
  "phone_number": "5554445555"
}

### Users delete action
DELETE http://localhost:3000/users/5.json



### Performers index request

GET http://localhost:3000/performers.json

### Performers show request

GET http://localhost:3000/performers/1.json