
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Njc5NTQyNTV9.Sy5_0ztYgfmGViuu30_Xreghw9P-7vTkMUL1OBD-hHE

### Sessions create
POST http://localhost:3000/login.json
Content-Type: application/json

{
  "email": "kyle@test.com",
  "password": "password"
}

### Users show request

GET http://localhost:3000/users/1.json
Authorization: Bearer {{jwt}}

### Users create action

POST http://localhost:3000/users.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "Test",
  "phone_number": "5558885555",
  "email": "tst@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users update action

PATCH http://localhost:3000/users/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "phone_number": "5555555555"
}

### Users delete action
DELETE http://localhost:3000/users/5.json
Authorization: Bearer {{jwt}}




### Performers index request

GET http://localhost:3000/performers.json

### Performers show request

GET http://localhost:3000/performers/1.json




### Bookings index request

GET http://localhost:3000/bookings.json
Authorization: Bearer {{jwt}}

### Bookings show request

GET http://localhost:3000/bookings/1.json
Authorization: Bearer {{jwt}}

### Bookings create action

POST http://localhost:3000/bookings.json
Content-Type: application/json

{
  "user_id": "2",
  "performer_id": "1",
  "location": "2301 N Highland Ave, Los Angeles, CA 90068",
  "event_type": "concert",
  "start_time": "2022-12-23T20:00:00.000Z",
  "end_time": "2022-12-24T00:00:00.000Z",
  "total": "600"
}

### Bookings update action

PATCH http://localhost:3000/bookings/2.json
Content-Type: application/json

{
  "event_type": "comedy show"
}

### Bookings delete action
DELETE http://localhost:3000/bookings/3.json



### Reviews index request

GET http://localhost:3000/reviews.json

### Reviews show request

GET http://localhost:3000/reviews/1.json

### Reviews create action

POST http://localhost:3000/reviews.json
Content-Type: application/json

{
  "booking_id": "2",
  "rating": "5",
  "comment": "This was fantastic!!!"
}

### Reviews update action

PATCH http://localhost:3000/reviews/2.json
Content-Type: application/json

{
  "rating": "4.75"
}

### Reviews delete action
DELETE http://localhost:3000/reviews/3.json
