User.create!([
  { first_name: "Michelle", last_name: "Visage", phone_number: "5556655555", email: "michelle@test.com", passowrd: "password", password_confirmation: "password", image_data: nil, is_admin: false },
  { first_name: "RuPaul", last_name: "Charles", phone_number: "5554445555", email: "ru@test.com", passowrd: "password", password_confirmation: "password", image_data: nil, is_admin: true },
  { first_name: "Ross", last_name: "Matthews", phone_number: "8885558888", email: "ross@test.com", passowrd: "password", password_confirmation: "password", image_data: nil, is_admin: false },
  { first_name: "Kyle", last_name: "Pazdel", phone_number: "+12333333335", email: "kyle@test.com", passowrd: "password", password_confirmation: "password", image_data: nil, is_admin: true },
  { first_name: "Test", last_name: "User", phone_number: "+12345674893", email: "email@email.com", passowrd: "password", password_confirmation: "password", image_data: nil, is_admin: false },
])
Performer.create!([
  { name: "Lady Bunny", phone_number: "+15556665555", email: "ladyb@email.com", shortest_gig: 60, longest_gig: 120, city: "New York", state: "NY", rate: 250, bio: "Lady Bunny, originally known as \"Bunny Hickory Dickory Dock\", is an American drag queen, nightclub DJ, actor, comedian, and event organizer. She is the founder of the annual Wigstock event, as well as an occasional television and radio personality.", instagram_handle: "official_lady_bunny", twitter_handle: "ladybunny77", performance_type: "comedy • singing • DJ", user_id: 1 },
  { name: "Katya Zamolodchikova", phone_number: "+15555555555", email: "katya@email.com", shortest_gig: 5, longest_gig: 15, city: "Boston", state: "MA", rate: 30, bio: "Yekaterina Petrovna Zamolodchikova, also known as Katya, is the stage name of the popular American drag queen, comedian, and reality TV star Brian Joseph McCook. Katya is best known for her stint on the reality show 'RuPaul's Drag Race.' The show established the identity of the drag character ‘Katya,’ a high-class Russian prostitute. Following the show, Brian adopted the persona of the drag queen. Katya is known for web series and talk shows such as 'UNHhhh' and 'The Trixie & Katya Show.' The latter was a talk show she hosted alongside fellow drag queen Trixie Mattel. Katya was addicted to drugs in the past. She often talks openly about her sexual orientation.", instagram_handle: "katya_zamo", twitter_handle: "katya_zamo", performance_type: "split, kick, and dip", user_id: 1 },
  { name: "Rock M Sakura", phone_number: "+19995559999", email: "", shortest_gig: 120, longest_gig: 800, city: "San Francisco", state: "CA", rate: 700, bio: "ROCK M Sakura is a beloved fan favorite from Rupauls Drag Race Season 12, and is the current reigning Miss Jpop SF. Sakura is usually found death dropping, hot-glueing, wearing short shorts, doing drop splits, working out her back rolls and scratching her head in confusion when she can't thread her sewing machine. She is heavily influenced by Manga and anime, which shows in her cartoonish louder than life make up style. A beautiful mix of fierce, camp, and kawaii, this is a high energy queen you won't want to miss!", instagram_handle: "rockmsakura", twitter_handle: "RockMSakura", performance_type: "comedy ", user_id: 1 },
  { name: "Trixie Mattel", phone_number: "+12345559000", email: "", shortest_gig: 10, longest_gig: 500, city: "Los Angeles", state: "CA", rate: 700, bio: "Trixie Mattel is an American singer, actor, drag queen and recognized “Skinny Legend.” Trixie is the winner of “RuPaul’s Drag Race All Stars” season 3 (originally competing on season 7). She is also a Billboard Heatseekers #1 charting recording artist (One Stone, 2018), a wildly successful touring act, and one half of a comic duo with Katya on YouTube (“UNHhhh” & Netflix's \"I Like To Watch\").\n", instagram_handle: "trixiemattel", twitter_handle: "trixiemattel", performance_type: "comedy", user_id: 1 },
  { name: "Bob the Drag Queen", phone_number: "+18885558888", email: "bobtidiq@email.com", shortest_gig: 30, longest_gig: 800, city: "Columbus", state: "GA", rate: 3000, bio: "The alter ego of non-binary comic/actor Caldwell Tidicue, “Bob The Drag Queen” describes herself as “hilarious, beautiful, talented and...humble.” Bob’s unabashed confidence won her the title of “America’s Next Drag Superstar” on season 8 of “RuPaul’s Drag Race,” multiple acting roles for HBO, Netflix, Sony Tristar, MTV, and VH1. Along with HBO’s first unscripted show, “We’re Here,” Bob has recently released her second comedy special, “Bob The Drag Queen Live at Caroline’s” available on iTunes, as well as season 4 of “Sibling Rivalry,\" the podcast she co-hosts with her drag sister Monét X Change. Bob is represented by ICM and managed by Producer Entertainment Group (PEG).", instagram_handle: "bobthedragqueen", twitter_handle: "thatonequeen", performance_type: "comedy • acting • radio", user_id: 1 },
])

Post.create!([
  { title: "monet profile image", user_id: 11, performer_id: 22 },
  { title: "monet glam", user_id: 11, performer_id: 22 },
  { title: "monet profile image", user_id: 13, performer_id: 23 },
  { title: "hair", user_id: 13, performer_id: 23 },
  { title: "monet ", user_id: 1, performer_id: 19 },
  { title: "dramatic red", user_id: 1, performer_id: 11 },
  { title: "It's the DRAMA MAMA.", user_id: 1, performer_id: 10 },
  { title: "test", user_id: 1, performer_id: 24 },
  { title: "trixie profile image", user_id: 1, performer_id: 1 },
  { title: "joey!", user_id: 1, performer_id: 3 },
  { title: "bob-profile image", user_id: 1, performer_id: 4 },
  { title: "purse first image", user_id: 1, performer_id: 4 },
  { title: "lady-bunny", user_id: 1, performer_id: 9 },
  { title: "trixie guitar", user_id: 1, performer_id: 1 },
  { title: "trixie phone", user_id: 1, performer_id: 1 },
  { title: "clown image", user_id: 1, performer_id: 19 },
])
ActiveStorage::Blob.create!([
  { key: "l9m0f6rp7czmjvp7cxseffq6e50a", filename: "trixie-guitar.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 622781, checksum: "02EjRKfQwcsGh3jAPTf1Gw==" },
  { key: "uo1294r780si2bov0oyfevpddjyi", filename: "trixie-phone.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 190140, checksum: "flQlzW0OhYxF62yScDqicg==" },
  { key: "ujz19dfqukh6ft8knwlbpd2eky0c", filename: "clown.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 960808, checksum: "oTW17166UfactzKgFQay9Q==" },
  { key: "f11rk2jwhiwrzk5krotvqta236gu", filename: "trixie-mattel.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 3718081, checksum: "4TBG448s7Hk06dx2tnMTCg==" },
  { key: "56014wp5cp4irh1b8no4xzxgzz5k", filename: "Joey_2.PNG", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 2594625, checksum: "nGTBIRWWg0eOqEk7WXiPEg==" },
  { key: "9ezrlx141g1sl49fox8olyv8r8zd", filename: "bob-tidiq.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 1090313, checksum: "zsRaL07DhpuojQUN1BIwlw==" },
  { key: "zpxb9ivj8j25hkjpiewpdxfe768t", filename: "purse-first.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 1072496, checksum: "rdlLqMHe4ciC2Wqq05rUEQ==" },
  { key: "72th2l41g3kxlll9j6be8pt85cl3", filename: "lady-bunny.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 1448790, checksum: "Y4TY6XwtlM5w4qMiWrW7UQ==" },
  { key: "hmhfwfave93n908s01ck41df25gp", filename: "monet-profile.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 843906, checksum: "7DsMU8JEwIXc518k1l/nYA==" },
  { key: "ifldfc7wx5zdreslemhadwr5flqt", filename: "monet-second.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 1291326, checksum: "CV+RYuJuNPwAxvRzA/p3qw==" },
  { key: "wlesr09cr4m3fomylncltlecnw96", filename: "monet-profile.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 843906, checksum: "7DsMU8JEwIXc518k1l/nYA==" },
  { key: "lldud3ms8ngiuf78atmtq97uertc", filename: "monet-second.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 1291326, checksum: "CV+RYuJuNPwAxvRzA/p3qw==" },
  { key: "gz89tlzhd2rb1ex46ze1u10ftokp", filename: "monet-second.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 1291326, checksum: "CV+RYuJuNPwAxvRzA/p3qw==" },
  { key: "oohm66covsx6kovn4kst49wp3pzy", filename: "katya-profile.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 2785118, checksum: "qZ44c30YxrZMHzQB9vzNRQ==" },
  { key: "hyatmgnd0xepwrk267yvrsg61hda", filename: "rock-profile-image.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 1365814, checksum: "fIoDhAtWd/02bWelH0FySg==" },
  { key: "gtery96ok7a3c8s8zjgek0eve5l3", filename: "monet-profile.png", content_type: "image/png", metadata: { "identified" => true, "analyzed" => true }, service_name: "local", byte_size: 843906, checksum: "7DsMU8JEwIXc518k1l/nYA==" },
])
ActiveStorage::Attachment.create!([
  { name: "image", record_type: "Post", record_id: 13, blob_id: 13 },
  { name: "image", record_type: "Post", record_id: 17, blob_id: 17 },
  { name: "image", record_type: "Post", record_id: 18, blob_id: 18 },
  { name: "image", record_type: "Post", record_id: 19, blob_id: 19 },
  { name: "image", record_type: "Post", record_id: 21, blob_id: 21 },
  { name: "image", record_type: "Post", record_id: 22, blob_id: 22 },
  { name: "image", record_type: "Post", record_id: 23, blob_id: 23 },
  { name: "image", record_type: "Post", record_id: 26, blob_id: 26 },
  { name: "image", record_type: "Post", record_id: 31, blob_id: 31 },
  { name: "image", record_type: "Post", record_id: 32, blob_id: 32 },
  { name: "image", record_type: "Post", record_id: 33, blob_id: 33 },
  { name: "image", record_type: "Post", record_id: 34, blob_id: 34 },
  { name: "image", record_type: "Post", record_id: 35, blob_id: 35 },
  { name: "image", record_type: "Post", record_id: 36, blob_id: 36 },
  { name: "image", record_type: "Post", record_id: 37, blob_id: 37 },
  { name: "image", record_type: "Post", record_id: 38, blob_id: 38 },
])
Booking.create!([
  { user_id: 2, performer_id: 1, address: "330 Pine Ave", event_type: "Christmas Party", start_time: "2022-12-25 01:00:00", end_time: "2022-12-25 07:00:00", total: 1800, event_name: "Michelle's Christmas Party 🎄", city: "Long Beach", state: "CA", postal_code: "90802", latitude: 33.770919652074205, longitude: -118.19228004494055, paid: nil },
  { user_id: 2, performer_id: 1, address: "275 W 22nd St", event_type: "Birthday Party", start_time: "2022-11-26 04:00:00", end_time: "2022-11-26 10:00:00", total: 1800, event_name: "Michelle's Birthday Extravaganza 🎉", city: "New York", state: "NY", postal_code: "10011", latitude: 40.7445405, longitude: -73.998373, paid: nil },
  { user_id: 2, performer_id: 1, address: "692 N Robertson Blvd", event_type: "Halloween Party!", start_time: "2023-11-01 01:00:00", end_time: "2023-11-01 09:00:00", total: 2400, event_name: "Michelle's Halloween Party 🎃 ", city: "West Hollywood", state: "California", postal_code: "90069", latitude: 34.0833871, longitude: -118.3851445, paid: nil },
  { user_id: 2, performer_id: 1, address: "2301 N Highland Ave", event_type: "concert", start_time: "2022-12-23 20:00:00", end_time: "2022-12-24 00:00:00", total: 600, event_name: "test event", city: "Los Angeles", state: "CA", postal_code: "90068", latitude: 34.11070069252548, longitude: -118.33634851989088, paid: false },
  { user_id: 2, performer_id: 10, address: "teste", event_type: "party", start_time: "2022-11-13 20:00:00", end_time: "2022-11-13 23:30:00", total: 0, event_name: "Test", city: "1639 S Andee Dr", state: "Palm Springs", postal_code: "92264", latitude: nil, longitude: nil, paid: false },
  { user_id: 1, performer_id: 4, address: "1639 S Andee Dr.", event_type: "Party", start_time: "2022-11-14 00:00:00", end_time: "2022-11-16 00:30:00", total: 145499, event_name: "Event", city: "Palm Springs", state: "CA", postal_code: "92262", latitude: 33.8031041, longitude: -116.5253072, paid: true },
  { user_id: 1, performer_id: 1, address: "1762 Pistacia Ct.", event_type: "Test Event", start_time: "2022-11-12 01:30:00", end_time: "2022-11-12 05:00:00", total: 2450, event_name: "Another TEST Event w/ Location!!!", city: "Fairfield", state: "California", postal_code: "94533", latitude: 38.30095228207533, longitude: -122.01404903458877, paid: true },
  { user_id: 1, performer_id: 1, address: "1639 S Andee Dr.", event_type: "Test", start_time: "2022-11-15 18:00:00", end_time: "2022-11-15 19:30:00", total: 1050, event_name: "Teset", city: "Palm Springs", state: "CA", postal_code: "92264", latitude: 33.8031041, longitude: -116.5253072, paid: true },
  { user_id: 1, performer_id: 1, address: "1639 S Andee Dr.", event_type: "Event", start_time: "2022-11-15 00:00:00", end_time: "2022-11-15 07:30:00", total: 5250, event_name: "Cool Party", city: "Palm Springs", state: "CA", postal_code: "92264", latitude: 33.8031041, longitude: -116.5253072, paid: true },
])
Review.create!([
  { booking_id: 3, rating: 5.0, comment: "Love this queen!", user_id: 2 },
  { booking_id: 3, rating: 4.0, comment: "Love this queen!", user_id: 2 },
  { booking_id: 12, rating: 2.0, comment: "Cool!", user_id: 1 },
  { booking_id: 12, rating: 3.5, comment: "Sweet job Gal!", user_id: 1 },
])
